PREFIX dblp:<https://dblp.org/rdf/schema-2020-07-01#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>

SELECT ?doi ?title
WHERE
{
    ?pub a dblp:Publication .
    ?pub dblp:title ?title .
    OPTIONAL { ?pub wdt:P356 ?doi . }
    ?pub dblp:yearOfPublication "2019" .
    ?pub dblp:authoredBy ?author .
    ?author dblp:primaryFullCreatorName ?name .
}
Limit 100
