PREFIX dblp:<https://dblp.org/rdf/schema-2020-07-01#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>

SELECT ?year (COUNT(?title) as ?no)
WHERE
{
    ?pub a dblp:Publication .
    ?pub dblp:title ?title .
    ?pub dblp:yearOfPublication ?year .
    ?pub dblp:publishedIn "Scientometrics" .
}
GROUP BY ?year ?no
