SELECT  ?title ?name ?input2 ?input1 ?input0
WHERE
{
    ?pub a <https://dblp.org/rdf/schema-2020-07-01#Publication> ;
    <https://dblp.org/rdf/schema-2020-07-01#yearOfPublication>  "2019" ;
    <https://dblp.org/rdf/schema-2020-07-01#authoredBy>  ?author .
    ?author  a <https://dblp.org/rdf/schema-2020-07-01#Person>
    OPTIONAL { ?pub     <https://dblp.org/rdf/schema-2020-07-01#title>  ?title  }
    OPTIONAL { ?author  <https://dblp.org/rdf/schema-2020-07-01#primaryFullCreatorName>  ?name }
    OPTIONAL { ?pub  <http://www.wikidata.org/prop/direct/P818>  ?input0 }
    OPTIONAL { ?pub  <http://www.wikidata.org/prop/direct/P356>  ?input1 }
    OPTIONAL { ?author  <http://www.wikidata.org/prop/direct/P496>  ?input2 }
}
