PREFIX dblp:<https://dblp.org/rdf/schema-2020-07-01#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>

SELECT ?doi ?title ?input0
WHERE
{
    {
        {
            ?pub a dblp:Publication .
            ?pub dblp:publishedIn "Scientometrics" .
            OPTIONAL { ?pub wdt:P356 ?doi . }
            OPTIONAL { ?pub dblp:title ?title . }
            OPTIONAL{ ?pub wdt:P818 ?input0 . }
        }
        UNION
        {
            ?pub a dblp:Publication .
            ?pub dblp:publishedIn "IEEE Trans. Pattern Anal. Mach. Intell" .
            OPTIONAL { ?pub wdt:P356 ?doi . }
            OPTIONAL { ?pub dblp:title ?title . }
            OPTIONAL{ ?pub wdt:P818 ?input0 . }
        }
    }
    UNION
    {
        ?pub a dblp:Publication .
        ?pub dblp:publishedIn "Theor. Comput. Sci." .
        OPTIONAL { ?pub wdt:P356 ?doi . }
        OPTIONAL { ?pub dblp:title ?title . }
        OPTIONAL{ ?pub wdt:P818 ?input0 . }
    }
}
