PREFIX dblp:<https://dblp.org/rdf/schema-2020-07-01#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>

SELECT ?year ?title
WHERE
{
    ?pub a dblp:Publication .
    ?pub dblp:publishedIn "SIGIR" .
    ?pub dblp:title ?title .
    ?pub dblp:yearOfPublication ?year .
}
ORDER BY DESC(?year) ?title
