PREFIX dblp:<https://dblp.org/rdf/schema-2020-07-01#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>

SELECT ?title
WHERE
{
    ?pub a dblp:Publication .
    ?pub dblp:yearOfPublication "2019" .
    ?pub dblp:title ?title .
}
Limit 100
