SELECT  ?year ?title ?input1 ?input0
WHERE
{
    ?pub  <https://dblp.org/rdf/schema-2020-07-01#title>  ?title ;
    <https://dblp.org/rdf/schema-2020-07-01#yearOfPublication>  ?year
    OPTIONAL { ?pub  <http://www.wikidata.org/prop/direct/P818>  ?input0 }
    OPTIONAL { ?pub  <http://www.wikidata.org/prop/direct/P356>  ?input1 }
}
