SELECT  ?name ?venue ?input1 ?input0
WHERE
{
    {
        {
            ?pub  a <https://dblp.org/rdf/schema-2020-07-01#Publication>
            OPTIONAL { ?pub  <http://www.wikidata.org/prop/direct/P818>  ?input0 }
            OPTIONAL { ?pub  <https://dblp.org/rdf/schema-2020-07-01#publishedIn>  ?venue }
        }
        ?pub  <https://dblp.org/rdf/schema-2020-07-01#authoredBy>  ?author
    }
    {
        ?author <https://dblp.org/rdf/schema-2020-07-01#primaryFullCreatorName>  ?name
        OPTIONAL { ?author  <http://www.wikidata.org/prop/direct/P496>  ?input1 }
    }
}
